// IndexNow submission.
//
// IndexNow tells Bing, Yandex, Seznam and Naver about changed URLs immediately
// instead of waiting for a crawl. Google does not participate, so Search Console
// remains the route for Google. Bing feeds Copilot, and ChatGPT search leans on
// Bing's index, so this also shortens the path to AI answer engines.
//
// SETUP (once):
//   1. Generate a key — any hex string of 8-128 characters:
//        node -e "console.log(crypto.randomUUID().replace(/-/g,''))"
//   2. Host it as a text file whose body is the key itself, at the site root:
//        public/<key>.txt        ->  https://elbilexpressen.no/<key>.txt
//      The file must contain the key and nothing else. This is how the API
//      verifies that you control the domain.
//   3. Put the same key in the environment:
//        INDEXNOW_KEY=<key>
//
// USAGE (after every deploy, not before — the URLs must already be live):
//   npm run build && npx wrangler deploy && INDEXNOW_KEY=<key> npm run indexnow
//
// Submitting a URL that 404s gets the whole batch rejected, which is why this
// runs after the deploy rather than as part of the build.

import { readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sitemapPath = join(root, 'dist', 'sitemap.xml');
const ENDPOINT = 'https://api.indexnow.org/indexnow';

const key = process.env.INDEXNOW_KEY;
if (!key) {
  console.error('INDEXNOW_KEY is not set. See the setup notes at the top of scripts/indexnow.mjs.');
  process.exit(1);
}

if (!/^[A-Za-z0-9-]{8,128}$/.test(key)) {
  console.error('INDEXNOW_KEY must be 8-128 characters, letters, digits and dashes only.');
  process.exit(1);
}

let sitemap;
try {
  sitemap = await readFile(sitemapPath, 'utf8');
} catch {
  console.error(`No sitemap at ${sitemapPath}. Run "npm run build" first.`);
  process.exit(1);
}

// The sitemap is generated by scripts/prerender.mjs and is the authoritative
// list of indexable URLs, so reading it keeps the two from drifting apart.
const urlList = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match => match[1].trim());

if (urlList.length === 0) {
  console.error('No <loc> entries found in the sitemap.');
  process.exit(1);
}

const host = new URL(urlList[0]).host;

const payload = {
  host,
  key,
  keyLocation: `https://${host}/${key}.txt`,
  urlList,
};

console.log(`Submitting ${urlList.length} URLs for ${host} to IndexNow...`);

const response = await fetch(ENDPOINT, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json; charset=utf-8' },
  body: JSON.stringify(payload),
});

const body = await response.text();

// 200 accepted, 202 accepted but key still being validated. Anything else is a
// real failure worth a non-zero exit so CI notices.
if (response.status === 200 || response.status === 202) {
  console.log(`  ${response.status} ${response.statusText} — accepted.`);
  for (const url of urlList) console.log(`    ${url}`);
  process.exit(0);
}

console.error(`  ${response.status} ${response.statusText}`);
if (body) console.error(`  ${body}`);
if (response.status === 403) {
  console.error(`  403 usually means ${payload.keyLocation} is missing or does not contain the key.`);
}
process.exit(1);
